name: Heat Snake

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - uses: Platane/snk@v3
        id: snake-gif
        with:
          github_user_name: NextEcho
          outputs: |
            dist/github-snake.svg
            dist/github-snake-dark.svg?palette=github-dark
            dist/ocean.gif?color_snake=orange&color_dots=#bfd6f6,#8dbdff,#64a1f4,#4b91f1,#3c7dd9

      - uses: actions/upload-artifact@v2
        with:
          name: snake-gif
          path: dist
          
      - name: Push to GitHub
        run: |
          git config --global user.name github-actions
          git config --global user.email github-actions@github.com
          git add dist/
          git commit -m "Generate Snake"
          git push